In [1]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler

/Users/troycassels/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
cd /Users/troycassels/Documents

/Users/troycassels/Documents

In [3]:
file_path = "Documents"

In [4]:
df = pd.read_csv(Path("Sample GPT tweets.csv"))

In [5]:
df.head()

,user_name,text,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,hashtags,source
0,Math_Maniac,ChatGPT does ascii art\n#ChatGPT https://t.co/...,"Decatur, GA",I work with a number of tools. Right now it's ...,2020-07-20 14:24:50+00:00,467.0,1233.0,49216,False,2023-04-02 13:44:07+00:00,['ChatGPT'],Twitter Web App
1,SmashKoders,#ChatGPT is funny sometimes 😅 https://t.co/cSa...,Mumbai,My life changed while debugging code 😊,2022-06-18 04:34:18+00:00,8.0,126.0,239,False,2023-04-02 13:43:46+00:00,['ChatGPT'],Twitter Web App
2,Andreas Illenseer,Let’s put it in graphic terms. Drawing a #Unic...,"Mainz, Deutschland",Specialized in Regulatory & Digital Intelligen...,2017-10-31 19:35:24+00:00,63.0,188.0,88,False,2023-04-02 13:43:36+00:00,['Unicorn'],Twitter for iPhone
3,Bitone Great,🔥#Buy!🔥\n🔥RSI below 15!🔥\n[#Bybit]\n⬆ Recommen...,NaN,#ChatGPT (AI) powered Free Trading Signal! \nL...,2022-11-21 04:42:18+00:00,1093.0,492.0,47,False,2023-04-02 13:43:30+00:00,"['Buy', 'Bybit', 'Long', 'DODOUSDT']",rsi1
4,The Media Scoop,Italian data protection agency placed an immed...,India,Independent news aggregator & YouTuber at The ...,2023-03-07 01:51:53+00:00,0.0,37.0,0,False,2023-04-02 13:42:56+00:00,NaN,Twitter Web App

In [6]:
df.iloc[0]

user_name                                                 Math_Maniac
text                ChatGPT does ascii art\n#ChatGPT https://t.co/...
user_location                                             Decatur, GA
user_description    I work with a number of tools. Right now it's ...
user_created                                2020-07-20 14:24:50+00:00
user_followers                                                  467.0
user_friends                                                   1233.0
user_favourites                                                 49216
user_verified                                                   False
date                                        2023-04-02 13:44:07+00:00
hashtags                                                  ['ChatGPT']
source                                                Twitter Web App
Name: 0, dtype: object

In [7]:
df["user_created"] =df["user_created"].apply(lambda x: pd.Timestamp(x).timestamp())

In [8]:
df["date"] =df["date"].apply(lambda x: pd.Timestamp(x).timestamp())

In [9]:
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sia= SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/troycassels/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [10]:
df['scores']=df['text'].apply(lambda body: sia.polarity_scores(str(body)))

In [11]:
df.head()

,user_name,text,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,hashtags,source,scores
0,Math_Maniac,ChatGPT does ascii art\n#ChatGPT https://t.co/...,"Decatur, GA",I work with a number of tools. Right now it's ...,1.595255e+09,467.0,1233.0,49216,False,1.680443e+09,['ChatGPT'],Twitter Web App,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
1,SmashKoders,#ChatGPT is funny sometimes 😅 https://t.co/cSa...,Mumbai,My life changed while debugging code 😊,1.655527e+09,8.0,126.0,239,False,1.680443e+09,['ChatGPT'],Twitter Web App,"{'neg': 0.0, 'neu': 0.58, 'pos': 0.42, 'compou..."
2,Andreas Illenseer,Let’s put it in graphic terms. Drawing a #Unic...,"Mainz, Deutschland",Specialized in Regulatory & Digital Intelligen...,1.509479e+09,63.0,188.0,88,False,1.680443e+09,['Unicorn'],Twitter for iPhone,"{'neg': 0.0, 'neu': 0.857, 'pos': 0.143, 'comp..."
3,Bitone Great,🔥#Buy!🔥\n🔥RSI below 15!🔥\n[#Bybit]\n⬆ Recommen...,NaN,#ChatGPT (AI) powered Free Trading Signal! \nL...,1.669006e+09,1093.0,492.0,47,False,1.680443e+09,"['Buy', 'Bybit', 'Long', 'DODOUSDT']",rsi1,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
4,The Media Scoop,Italian data protection agency placed an immed...,India,Independent news aggregator & YouTuber at The ...,1.678154e+09,0.0,37.0,0,False,1.680443e+09,NaN,Twitter Web App,"{'neg': 0.107, 'neu': 0.893, 'pos': 0.0, 'comp..."

In [12]:
df.iloc[0]

user_name                                                 Math_Maniac
text                ChatGPT does ascii art\n#ChatGPT https://t.co/...
user_location                                             Decatur, GA
user_description    I work with a number of tools. Right now it's ...
user_created                                             1595255090.0
user_followers                                                  467.0
user_friends                                                   1233.0
user_favourites                                                 49216
user_verified                                                   False
date                                                     1680443047.0
hashtags                                                  ['ChatGPT']
source                                                Twitter Web App
scores              {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...
Name: 0, dtype: object

In [13]:
df.dtypes

user_name            object
text                 object
user_location        object
user_description     object
user_created        float64
user_followers      float64
user_friends        float64
user_favourites       int64
user_verified          bool
date                float64
hashtags             object
source               object
scores               object
dtype: object

In [14]:
X_not_categorical = df[["user_created","user_followers","user_friends","user_favourites","date"]]
X_not_categorical.head()

   user_created  user_followers  user_friends  user_favourites          date
0  1.595255e+09           467.0        1233.0            49216  1.680443e+09
1  1.655527e+09             8.0         126.0              239  1.680443e+09
2  1.509479e+09            63.0         188.0               88  1.680443e+09
3  1.669006e+09          1093.0         492.0               47  1.680443e+09
4  1.678154e+09             0.0          37.0                0  1.680443e+09

In [15]:
X_categorical_exc_location = df[["user_verified","source"]]
X_categorical_exc_location.head()

   user_verified              source
0          False     Twitter Web App
1          False     Twitter Web App
2          False  Twitter for iPhone
3          False                rsi1
4          False     Twitter Web App

In [16]:
X_categorical_exc_location = pd.get_dummies(X_categorical_exc_location)
X_categorical_exc_location.head()

,user_verified,source_Buffer,source_Constant Contact - Social Posts,source_Hootsuite Inc.,source_IFTTT,source_Make (formerly Integromat),source_Metricool,source_Missinglettr,source_Nelio Content,source_SocialChamp IO,source_Sprout Social,source_TweetDeck,source_Twitter Web App,source_Twitter for Android,source_Twitter for iPhone,source_rsi1
0,False,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,False,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,False,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,False,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [17]:
X = pd.concat([X_not_categorical, X_categorical_exc_location], axis=1)
X.head()

,user_created,user_followers,user_friends,user_favourites,date,user_verified,source_Buffer,source_Constant Contact - Social Posts,source_Hootsuite Inc.,source_IFTTT,...,source_Metricool,source_Missinglettr,source_Nelio Content,source_SocialChamp IO,source_Sprout Social,source_TweetDeck,source_Twitter Web App,source_Twitter for Android,source_Twitter for iPhone,source_rsi1
0,1.595255e+09,467.0,1233.0,49216,1.680443e+09,False,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,1.655527e+09,8.0,126.0,239,1.680443e+09,False,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,1.509479e+09,63.0,188.0,88,1.680443e+09,False,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1.669006e+09,1093.0,492.0,47,1.680443e+09,False,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,1.678154e+09,0.0,37.0,0,1.680443e+09,False,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [18]:
def vader_scores(text, category):
    return vader.polarity_scores(text).get(category)

vader = SentimentIntensityAnalyzer()

df["Negative_Score"] = df.apply(lambda row : vader_scores(df["text"][row.name], "neg"),axis=1)
df["Neutral_Score"] = df.apply(lambda row : vader_scores(df["text"][row.name], "neu"),axis=1)
df["Positive_Score"] = df.apply(lambda row : vader_scores(df["text"][row.name], "pos"),axis=1)
df["Compound_Score"] = df.apply(lambda row : vader_scores(df["text"][row.name], "compound"),axis=1)

In [19]:
df.head(10)

,user_name,text,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,hashtags,source,scores,Negative_Score,Neutral_Score,Positive_Score,Compound_Score
0,Math_Maniac,ChatGPT does ascii art\n#ChatGPT https://t.co/...,"Decatur, GA",I work with a number of tools. Right now it's ...,1.595255e+09,467.0,1233.0,49216,False,1.680443e+09,['ChatGPT'],Twitter Web App,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,1.000,0.000,0.0000
1,SmashKoders,#ChatGPT is funny sometimes 😅 https://t.co/cSa...,Mumbai,My life changed while debugging code 😊,1.655527e+09,8.0,126.0,239,False,1.680443e+09,['ChatGPT'],Twitter Web App,"{'neg': 0.0, 'neu': 0.58, 'pos': 0.42, 'compou...",0.000,0.580,0.420,0.4404
2,Andreas Illenseer,Let’s put it in graphic terms. Drawing a #Unic...,"Mainz, Deutschland",Specialized in Regulatory & Digital Intelligen...,1.509479e+09,63.0,188.0,88,False,1.680443e+09,['Unicorn'],Twitter for iPhone,"{'neg': 0.0, 'neu': 0.857, 'pos': 0.143, 'comp...",0.000,0.857,0.143,0.7574
3,Bitone Great,🔥#Buy!🔥\n🔥RSI below 15!🔥\n[#Bybit]\n⬆ Recommen...,NaN,#ChatGPT (AI) powered Free Trading Signal! \nL...,1.669006e+09,1093.0,492.0,47,False,1.680443e+09,"['Buy', 'Bybit', 'Long', 'DODOUSDT']",rsi1,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,1.000,0.000,0.0000
4,The Media Scoop,Italian data protection agency placed an immed...,India,Independent news aggregator & YouTuber at The ...,1.678154e+09,0.0,37.0,0,False,1.680443e+09,NaN,Twitter Web App,"{'neg': 0.107, 'neu': 0.893, 'pos': 0.0, 'comp...",0.107,0.893,0.000,-0.5574
5,Game Development Daily News,Will your games be marketed by ChatGPT? https:...,NaN,Your source for daily news about game developm...,1.599147e+09,2525.0,724.0,1108,False,1.680443e+09,"['gamedev', 'gamedevelopment', 'indiedev', 'AI...",Twitter Web App,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,1.000,0.000,0.0000
6,Simon Hodgkins,Italian minister says country's ban on ChatGPT...,Global | Ireland | USA,President | Founder | CMO | Editor in Chief,1.287299e+09,6364.0,296.0,23528,False,1.680443e+09,NaN,Twitter for iPhone,"{'neg': 0.104, 'neu': 0.896, 'pos': 0.0, 'comp...",0.104,0.896,0.000,-0.5574
7,Khaled,https://t.co/MBDVVcTrqW . For Sale :\n\n🔥 Suit...,NaN,https://t.co/WamqNL2OVC https://t.co/kZaVTeRp...,1.580991e+09,1306.0,564.0,7763,False,1.680443e+09,['Meta'],Twitter Web App,"{'neg': 0.0, 'neu': 0.909, 'pos': 0.091, 'comp...",0.000,0.909,0.091,0.4767
8,Vivek Ahuja,How to keep your start-up relevant in 2023:\n\...,"Mumbai, India",Run an Audio Production House | Manage Artists...,1.475162e+09,8.0,88.0,32,False,1.680443e+09,['ChatGPT'],Twitter Web App,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,1.000,0.000,0.0000
9,Myindianow,ChatGPT will not replace people. But people wh...,"Pune, India",🇮🇳,1.646190e+09,14.0,33.0,52,False,1.680443e+09,"['ChatGPT', 'OpenAI', 'AIart']",Twitter for Android,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,1.000,0.000,0.0000

In [20]:
df.tail(10)

,user_name,text,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,hashtags,source,scores,Negative_Score,Neutral_Score,Positive_Score,Compound_Score
90,Bitone Great,🚨Time to Buy!🚨\n💰#Binance Spot💰\n⬆️ Recommenda...,NaN,#ChatGPT (AI) powered Free Trading Signal! \nL...,1.669006e+09,1093.0,492.0,47,False,1.680441e+09,"['Binance', 'Long', 'IOTXUSDT']",rsi1,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,1.000,0.000,0.0000
91,Dr. Monika Sonu I Founder Healthinnovationtoolbox,#AI News &amp; Highlights: March 2023 \nby Ste...,Bangalore,HIMSSFUTURE50-INNOVATION LEADER https://t.co/...,1.533366e+09,15822.0,12403.0,29194,False,1.680441e+09,"['AI', 'technology', 'data', 'ArtificialIntell...",Twitter Web App,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,1.000,0.000,0.0000
92,Bitone Great,🚨Get In!🚨\n💰#Binance Spot💰\n⬆️ Recommendation:...,NaN,#ChatGPT (AI) powered Free Trading Signal! \nL...,1.669006e+09,1093.0,492.0,47,False,1.680441e+09,"['Binance', 'Long', 'ARPAUSDT']",rsi1,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,1.000,0.000,0.0000
93,Pirate Mike,#ChatGPT is a tool do not become dependent upo...,"Bristol, VA",Author | Crypto Educator | Investor | Mental H...,1.665755e+09,513.0,4935.0,1698,False,1.680441e+09,['ChatGPT'],Twitter for iPhone,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,1.000,0.000,0.0000
94,Most Bay▶️,"RiverRise(.)com SOLD for $2,288 -BuyDomains, A...",JakartaX.com,Investor in #Crypto & #DomainNames. Selling: h...,1.347730e+09,2343.0,4338.0,15594,False,1.680441e+09,NaN,Twitter Web App,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,1.000,0.000,0.0000
95,fracksix,#ChatGPT cannot save us. https://t.co/tmAMM5zdzu,NaN,NaN,1.678213e+09,3.0,28.0,0,False,1.680441e+09,['ChatGPT'],Twitter for iPhone,"{'neg': 0.396, 'neu': 0.604, 'pos': 0.0, 'comp...",0.396,0.604,0.000,-0.3875
96,Kalina Kalinova,FREE Social Ping Submission 138 Directories\nh...,NaN,NaN,1.675222e+09,107.0,387.0,249,False,1.680441e+09,"['FREE', 'Social', 'Ping', 'Submission', 'Dire...",Twitter Web App,"{'neg': 0.0, 'neu': 0.776, 'pos': 0.224, 'comp...",0.000,0.776,0.224,0.6166
97,Sundar Narasimhan,Great discussion at @theallinpod esp. regardin...,NaN,NaN,1.329684e+09,99.0,1058.0,1175,False,1.680441e+09,NaN,Twitter for Android,"{'neg': 0.0, 'neu': 0.866, 'pos': 0.134, 'comp...",0.000,0.866,0.134,0.7096
98,Most Bay▶️,"ClientFinancing(.)com SOLD for $2,288 -BuyDoma...",JakartaX.com,Investor in #Crypto & #DomainNames. Selling: h...,1.347730e+09,2343.0,4338.0,15594,False,1.680441e+09,NaN,Twitter Web App,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,1.000,0.000,0.0000
99,Alvaro Ramirez,chatgpt-shell now offers a post-processing cus...,"In Emacs, somewhere in London",https://t.co/cWRvlp5UQ0,1.267626e+09,523.0,1097.0,1251,False,1.680441e+09,NaN,Twitter Web App,"{'neg': 0.0, 'neu': 0.902, 'pos': 0.098, 'comp...",0.000,0.902,0.098,0.3612

In [21]:
y = df["Compound_Score"]

In [22]:
y.head()

0    0.0000
1    0.4404
2    0.7574
3    0.0000
4   -0.5574
Name: Compound_Score, dtype: float64

In [23]:
X.head()

,user_created,user_followers,user_friends,user_favourites,date,user_verified,source_Buffer,source_Constant Contact - Social Posts,source_Hootsuite Inc.,source_IFTTT,...,source_Metricool,source_Missinglettr,source_Nelio Content,source_SocialChamp IO,source_Sprout Social,source_TweetDeck,source_Twitter Web App,source_Twitter for Android,source_Twitter for iPhone,source_rsi1
0,1.595255e+09,467.0,1233.0,49216,1.680443e+09,False,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,1.655527e+09,8.0,126.0,239,1.680443e+09,False,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,1.509479e+09,63.0,188.0,88,1.680443e+09,False,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1.669006e+09,1093.0,492.0,47,1.680443e+09,False,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,1.678154e+09,0.0,37.0,0,1.680443e+09,False,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [24]:
# Split data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [25]:
# Instantiate a StandardScaler instance
scaler = StandardScaler()

# Fit the training data to the standard scaler
X_scaler = scaler.fit(X_train)

# Transform the training data using the scaler
X_train_scaled = X_scaler.transform(X_train)

# Transform the testing data using the scaler
X_test_scaled = X_scaler.transform(X_test)